if (IHSLIB_HID_SDL_USE_SDL2)
    set(IHSLIB_SDL_TARGETVERSION "${SDL2_VERSION}")
    set(IHSLIB_HID_SDL_LIBRARIES ${SDL2_LIBRARIES})
    set(IHSLIB_HID_SDL_INCLUDE_DIRS ${SDL2_INCLUDE_DIRS})
else ()
    set(IHSLIB_SDL_TARGETVERSION "${SDL3_VERSION}")
    set(IHSLIB_HID_SDL_LIBRARIES ${SDL3_LIBRARIES})
    set(IHSLIB_HID_SDL_INCLUDE_DIRS ${SDL3_INCLUDE_DIRS})
endif ()

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$" SDL_SEMVER "${IHSLIB_SDL_TARGETVERSION}")
if (SDL_SEMVER)
    set(IHSLIB_SDL_TARGET_MAJOR ${CMAKE_MATCH_1})
    set(IHSLIB_SDL_TARGET_MINOR ${CMAKE_MATCH_2})
    set(IHSLIB_SDL_TARGET_PATCH ${CMAKE_MATCH_3})
else()
    set(IHSLIB_SDL_TARGET_MAJOR SDL_MAJOR_VERSION)
    set(IHSLIB_SDL_TARGET_MINOR SDL_MINOR_VERSION)
    set(IHSLIB_SDL_TARGET_PATCH SDL_PATCHLEVEL)
endif ()

set(GEN_INCLUDE_DIR ${CMAKE_CURRENT_BINARY_DIR}/gen_include)

add_library(ihslib-hid-sdl STATIC)
target_link_libraries(ihslib-hid-sdl PUBLIC ihslib PRIVATE ihs-protobuf ${IHSLIB_HID_SDL_LIBRARIES})
target_include_directories(ihslib-hid-sdl PUBLIC include ${GEN_INCLUDE_DIR} SYSTEM PUBLIC ${IHSLIB_HID_SDL_INCLUDE_DIRS} PRIVATE ../..)
if (IHSLIB_HID_SDL_USE_SDL2)
    target_compile_definitions(ihslib-hid-sdl PUBLIC IHSLIB_HID_SDL2=1)
endif ()

add_subdirectory(src)
